version: '3.7'
services:
  api:
    container_name: api
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db
    command: ["npm","start"]
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'restapi'
    
    ports:
      - 5431:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:

